"$schema" = 'https://starship.rs/config-schema.json'

format = """
[â–‘â–’â–“](#FF9966)\
[ Frasier ](bg:#FF9966 fg:#2C1810)\
[îƒ„](bg:#FFD4A3 fg:#FF9966)\
$directory\
[îƒ„](fg:#FFD4A3 bg:#4A90A4)\
$git_branch\
$git_status\
$git_state\
[îƒ„](fg:#4A90A4 bg:#87CEEB)\
$nodejs\
$python\
$rust\
$golang\
$php\
[îƒ„](fg:#87CEEB bg:#E8B4A0)\
$time\
[î‚´](fg:#E8B4A0)\
\n$character
"""

[character]
success_symbol = '[>](bold #66CC99)'
error_symbol = '[>](bold #FF6B6B)'

[directory]
style = "fg:#2C1810 bg:#FFD4A3"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[git_branch]
symbol = "î‚ "
style = "bg:#4A90A4"
format = '[[ $symbol $branch ](fg:#E6F7FF bg:#4A90A4)]($style)'

[git_status]
style = "bg:#4A90A4"
format = '[[($all_status$ahead_behind )](fg:#E6F7FF bg:#4A90A4)]($style)'

[git_state]
style = "bg:#4A90A4"
cherry_pick = '[ğŸ’ PICKING]'
merge = '[ğŸŒ³ MERGING]'
rebase = '[ğŸŒµ REBASING]'
revert = '[ğŸ”™ REVERTING]'
format = '[[\($state( $progress_current of $progress_total)\)](fg:#E6F7FF bg:#4A90A4)]($style) '

[nodejs]
symbol = ""
style = "bg:#87CEEB"
format = '[[ $symbol ($version) ](fg:#2C1810 bg:#87CEEB)]($style)'

[rust]
symbol = ""
style = "bg:#87CEEB"
format = '[[ $symbol ($version) ](fg:#2C1810 bg:#87CEEB)]($style)'

[golang]
symbol = ""
style = "bg:#87CEEB"
format = '[[ $symbol ($version) ](fg:#2C1810 bg:#87CEEB)]($style)'

[php]
symbol = ""
style = "bg:#87CEEB"
format = '[[ $symbol ($version) ](fg:#2C1810 bg:#87CEEB)]($style)'

[python]
symbol = "ğŸ"
style = "bg:#87CEEB"
format = '[[ $symbol ($version) ($virtualenv) ](fg:#2C1810 bg:#87CEEB)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#E8B4A0"
format = '[[ ïº $time ](fg:#2C1810 bg:#E8B4A0)]($style)'
